spring.application.name=analytics

# ---------------- DB ----------------
spring.datasource.url=jdbc:postgresql://localhost:5432/analytics
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---------------- KAFKA ----------------
spring.kafka.bootstrap-servers=localhost:9092

# Producer config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer config
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON trust
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#Reddis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# OpenAI key from environment (with default empty for development)
openai.api.key=${OPENAI_API_KEY:}